### ISSUE TITLE
warnings from pytest

### ISSUE THREAD

**Issue by FC4R** [BESTenergytrade/simply#184]
There are a lot of warnings when running python -m pytest...?

**Comment by j-ti** [comment]
These are expected warnings, that are tested by running commands within a context e.g. `with pytest.warns(UserWarning ...`

We could check if it makes sense to suppress the terminal print in those cases

**Comment by j-ti** [comment]
either
```
# pytest.ini
[pytest]
filterwarnings =
    error
    ignore::UserWarning
    ignore:function ham\(\) is deprecated:DeprecationWarning
```
or e.g. running
`pytest -q tests -W ignore::UserWarning`

**Comment by j-ti** [comment]
But ultimately a warning is not an error, the tests are designed in a way to make sure everything works as expected and warnings only helps a user not familiar with the software to understand  what is happening. The tests already take that into consideration ...

**Comment by j-ti** [comment]
There have to be tests that create a condition, so that the warning is prompted as wanted, and there are ways to make sure they do as explained in comment https://github.com/BESTenergytrade/simply/issues/184#issuecomment-1591067991
When suppressing the warnings, that would only consider the CI and the command to test in README.md and not in the code. The idea would be to avoid confusion. However, test are generally nothing nothing that should concern the user, as the developer construct the tests -while considering the warnings- in order to fail in case sth. actually wents wrong. 

Besides pytest, regarding execution of main.py, the user is informed that for example a default value is used, if a parameter was not set by the user, so indeed it shows a risk for unwanted behavior. There are more possibilities to inform the user, e.g. using the logging lib, to log also other categories such as info, debug, warnings, handled errors etc., the logging scope can then be defined in an python arg along with the simply_config.
